### PR TITLE
Add Speedshop blog

### PR DESCRIPTION
**Pull request by nateberkopec**

### CODE REVIEW

**Comment by jrochkind** [comment]
Thanks! Is there no page on your own site that lists recent blog entries, a list/index view?

**Comment by nateberkopec** [comment]
https://www.speedshop.co/blog

**Comment by jrochkind** [comment]
Hi, the fetcher isn't currently following redirects, so I needed to change the `http://www.speedshop.co/feed.xml` in your PR into `https://www.speedshop.co/feed.xml`. 

Plan to make a suggest submission form that will do a preview and hopefully make it easier to avoid mistakes like that.

**Comment by jrochkind** [comment]
Hm, and for some reason it's still having trouble parsing your feed. I'll have to debug it more later.

**Comment by nateberkopec** [comment]
Could definitely just be my feed, I've had problems in the past. LMK, but it does seem to validate OK enough.

**Comment by jrochkind** [comment]
Aha. 

This post: https://www.speedshop.co/2015/11/30/how-changing-webfonts-made-rubygems-10x-faster.html

Contains in it an img tag with a bad src URI:  ``

But my code should not choke on a bad URI.  They reason it is looking at URIs at all, is becuase some people's feeds return _relative_ URLs in img src and a hrefs, and the code is trying to resolve them to be absolute.  But when it runs into one that's not a recognizable URI, it chokes. I'll fix it so it doesn't.

**Comment by jrochkind** [comment]
In the meantime though, if you fix that, your feed will be included succesfully on next regularly scheduled crawl.

**Comment by jrochkind** [comment]
Next problem though is that your recent post "Rubyconf 2016: The Performance Update" does not appear in the feed at all, so would not have been on rubyland.news anyway.

**Comment by nateberkopec** [comment]
Fixed, thanks for helping me debug :)

**Comment by jrochkind** [comment]
Likewise! Problem cases are good for making sure rubyland is robust!

**Pull request merged**
